### ISSUE TITLE
Authentication is randomly lost on macOS

### ISSUE THREAD

**Issue by jfro** [git-ecosystem/git-credential-manager#1249] opened 2023-05-12 14:58 UTC
### Version

2.0.931+f99d745b98

### Operating system

macOS

### OS version or distribution

Ventura 13.3.1 (a) (22E772610a)

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I try to clone/use git & get authentication UI & I authenticate & don't have to do it again anytime soon

### Actual behavior

After 1-3 days I get spammed with numerous Github.UI instances (From Xcode and/or Fork GUI apps) and CLI git also will cause a auth UI to pop, like it suddenly forgot authentication.
![image](https://github.com/git-ecosystem/git-credential-manager/assets/41898/b413c809-0ee2-4d17-90ca-03e69a67aa60)

**Comment by mjcheetham** [comment] 2023-05-12 15:01
> Github.UI instances (From Xcode and/or Fork GUI apps)

Can I ask what version of Xcode you are using? Did you recently update Xcode?

**Comment by jfro** [comment] 2023-05-15 14:46
Xcode 14.3, haven't updated it super recently that I recall. Though 14.3 is current stable (March 30th)

**Comment by mjcheetham** [comment] 2023-05-15 21:32
We've identified an issue with the keychain interaction of GCM when started inside of Xcode 14.3 and are actively investigating.

In the mean time, disabling the 'auto fetch' feature in Xcode will stop these unexpected 'nuking' of the keychain entry, and avoiding using `fetch` or `push` from Xcode.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/5658207/a88501c1-8a15-49dc-9ca6-e35cb26a5292)


See https://github.com/git-ecosystem/git-credential-manager/issues/1157
Closing as duplicate of https://github.com/git-ecosystem/git-credential-manager/issues/1157

**Closed by mjcheetham** 2023-05-15 21:32 UTC
Labels: platform:osx, auth-issue
