### ISSUE TITLE
Using Wayland causes a black box to be shown instead of the login prompt

### ISSUE THREAD

**Issue by CicadaCinema** [git-ecosystem/git-credential-manager#1113] opened 2023-02-14 19:29 UTC
### Version

2.0.886+ea93cb5158

### Operating system

Linux

### OS version or distribution

Fedora Linux 37; Kernel Version: 6.1.10-200.fc37.x86_64 (64-bit)

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Running `git pull` prompts me with a GUI pop-up, allowing me to authenticate myself.

### Actual behavior

A GUI window pops up with black contents, similar to the screenshot in https://github.com/GitCredentialManager/git-credential-manager/issues/1027 .

**Comment by ldennington** [comment] 2023-03-07 23:39
Closing - duplicate of #1027

**Closed by ldennington** 2023-03-07 23:39 UTC
Labels: auth-issue
