### ISSUE TITLE
`git-credential-manager-core`'s CPU usage peaks on Mac

### ISSUE THREAD

**Issue by ANTARES-KOR** [git-ecosystem/git-credential-manager#939] opened 2022-11-03 10:04 UTC
**Which version of GCM are you using?**

2.0.785+6074e4e3d3 (macOS Monterey 12.4, M1 pro)

I have a CPU usage issue with My Mac.

![스크린샷 2022-11-03 오후 6 50 27](https://user-images.githubusercontent.com/75557859/199692689-cf201acf-d702-471a-be70-d18437dbd9c2.png)

Suddenly Mac's CPU usage peaks, and I found that multiple `git-credential-manager-core` processes were consuming my CPU.

This happens occasionally (like 2 times a day..?) 
Is there any possible reason for this?

**Comment by mjcheetham** [comment] 2022-11-03 17:30
Hello @ANTARES-KOR,

That's a lot of instances running! Something must be running Git commands in the background periodically. Please can switch Activity Monitor to the "All Processes, Hierarchically" view and see the parent processes from GCM to see what is triggering us?

Do you use any 'auto-fetch' features in any editors/IDEs, or use any Git tools other than the `git` command-line?

<img width="298" alt="image" src="https://user-images.githubusercontent.com/5658207/199791605-e8046030-efe1-40bb-9e6a-87d5402bb8a0.png">

<img width="297" alt="image" src="https://user-images.githubusercontent.com/5658207/199792108-26243bce-437b-4470-9fb5-ce6effb9c4c3.png">


You can also set the `GCM_TRACE` environment variable to an absolute file path to have all GCM instances write out trace information to that file, on the next GCM start. (remember to restart all terminal instances and tools after updating the profile)

```shell
# zsh
echo "export GCM_TRACE=/tmp/gcm.log" >> ~/.zshrc

# bash
echo "export GCM_TRACE=/tmp/gcm.log" >> ~/.bashrc
```

**Comment by ANTARES-KOR** [comment] 2022-11-04 01:22
I'm currently using Github Desktop & vscode with auto fetch enabled.
Maybe this could be a reason! 

I'll test with these options disabled. If problem happens again, I'll update to this issue.

Thanks for all your support and fast response! :)

**Comment by ldennington** [comment] 2022-11-08 18:19
Going to close for now - @ANTARES-KOR please feel free to re-open if disabling the options doesn't work or you start to see this issue again.

**Comment by me4502** [comment] 2022-11-15 01:03
I seem to be having a somewhat similar issue to this. There aren't a lot of instances, however it's using an entire CPU core if I keep the Terminal open, from the moment I run a git command. It seems something is persisting?

If I run `ps aux | grep git`, the only entry aside from the grep is `/usr/local/share/gcm-core/git-credential-manager-core get`

<img width="460" alt="image" src="https://user-images.githubusercontent.com/546754/201800723-a0803373-463d-4b30-be90-4ce5907cc7fe.png">

Running macOS 13.0.1

**Comment by ldennington** [comment] 2022-11-15 23:47
@me4502 - can you please follow the [TRACE instructions that @mjcheetham called out above](https://github.com/GitCredentialManager/git-credential-manager/issues/939#issuecomment-1302446243), re-run the Git command in question, and send over the results (redacting as needed)? This will hopefully help us get some additional visibility into your issue.

**Comment by yoadsn** [comment] 2022-11-23 16:03
FWIW, since upgrading GCM a couple days ago AND moving to use OAuth and not PATs I see similar behavior - VS code UI lags, and mouse pointer jitter.

System is M1 Pro macOS 12.4.
GCM is 2.0.785+6074e4e3d3

Most noticeable, when opening a VS code workspace with ~10 repos.
VS Code has it's "source control" panel open, Git Lens, Git Graph, Github PRs extensions installed. (But disabling all extensions did seem to have an affect - maybe VS code itself pushes this to the limit).

I was able to spot the activity monitor showing > 7 instances of GCM running just like the OP had - all with high CPU consumption. Was not on the "hierarchical view" though.
(Azure DevOps repos mostly, and a couple of GH repos)

Last. I have been working with all those extensions and the multi repo for a long while without trouble. The only difference was moving to OAuth from PAT and upgrading GCM.

**Comment by me4502** [comment] 2022-11-25 04:24
I haven't been able to reproduce the issue I mentioned with the logging enabled. My only guess is that because logging seems to make it take ~10-20 seconds to do a push, it might be changing the run order of whatever was causing the issue.

**Comment by yoadsn** [comment] 2022-11-27 11:29
For me, I see that VS Code is configured to perform "AutoFetch" and do that every "180" (secs).

![image](https://user-images.githubusercontent.com/1684709/204132825-dd8fab94-d7ec-4d37-a857-c325fff6926a.png)

Every time this auto fetch process runs, the VS code would show logs for the "git" like the following:
```
2022-11-27 13:24:10.268 [info] > git fetch [4831ms]
2022-11-27 13:24:10.288 [info] > git remote --verbose [17ms]
2022-11-27 13:24:10.290 [info] > git config --get commit.template [17ms]
2022-11-27 13:24:10.292 [info] > git status -z -uall [20ms]
... more - for every repo in the workspace...
```

That "fetch" row takes anywhere from 2 - 6 seconds. While this takes place, CPU is high (GCM being the consumer).

I will disable the AutoFetch - but again - this is something I have used for years. This is not the root cause here - but rather the time it takes to perform this auto fetch and the amount of CPU it consumes.

**Comment by yoadsn** [comment] 2022-12-05 07:12
@ldennington Would love to know if we can provide more info on this to move fwd with researching.

**Comment by yoadsn** [comment] 2023-01-17 15:28
@ldennington  I had to look a bit deeper since this is such a bad experience I am having.

Some more info:
- From all the traces I gathered - seems like no caching is used - every time an a remote access is needed the oAuth flow is invoked (while oAuth flow is enabled - I am using Azure Devops repos).
- Checking the code - indeed it seems like for PATs a cache is consulted but for oAuth it is not?
https://github.com/GitCredentialManager/git-credential-manager/blob/02204ac1ffb78a7a361d57b8f9acd03e00de79aa/src/shared/Microsoft.AzureRepos/AzureReposHostProvider.cs#L76-L111

Specifically - looks like PAT is the only method that will have a cache consulted for `AzureReposHostProvider`.

Am I reading this right? Since this is 100% aligned with the fact this problem started when I moved to oAuth from PATs (which were bad, but in a different way).


Thanks!

**Comment by joaocc** [comment] 2023-02-25 08:49
Hi. 
Also having this issue, in macOS Ventura running on M1. 
We configured Sourcetree is indeed configured to do periodic polling, but the issue is that the number of processes that end up being launched get 100% CPU usage for a time much greater than before.
We do indeed also use PATs for most repos.
Thanks

**Comment by ldennington** [comment] 2023-03-07 23:28
Curious that this only affects Azure Repos for OAuth mode (not PAT mode). This could indicate a concurrency issue with the MSAL Cache Synchronization library. For those experiencing this problem, the workaround is to switch to PAT mode as we continue to investigate.

**Comment by forivall** [comment] 2023-03-15 20:54
I got annoyed enough at this that I [created a python script](https://gist.github.com/forivall/b47120eb0df9a6fe768e99ec15a85d53#file-git-credential-manager-reaper-py) to just automatically kill long running git-credential-manager instances

**Comment by yoadsn** [comment] 2023-03-20 05:53
> automatically kill long running git-credential-manager instances

Mmm, I would do that if I thought that would help - those long running processes are doing something. So you kill the and the git action that follows is not failing? It is able to use the stored oauth credentials?


@ldennington 
> as we continue to investigate.
I thought I pointed you guys in the right direction - there is no cache usage and the oAuth process is done from scratch each time. That means there is no usage of the existing token, instead a new flow produces a new token from what I see in the code. Have you arrived at the same conclusion?

**Comment by forivall** [comment] 2023-03-20 18:22
> > automatically kill long running git-credential-manager instances
> 
> Mmm, I would do that if I thought that would help - those long running processes are doing something. So you kill the and the git action that follows is not failing? It is able to use the stored oauth credentials?

I kill it and nothing bad happens, because they've probably been launched from background `git fetch`es which can just be re-done at some other point. Like in the original screenshot, I can see like 6 gcm instances running and apparently doing nothing, and I dont see anything complain when I kill them. The script only kills them when they've been running for at least 5 minutes, so if they havent finished it by then, they've already failed. Like, the linux git repo is 1.5GB, and on my connection, that wouldnt take more than 1 minute to download.

**Comment by joaocc** [comment] 2023-03-20 21:40
You were more patient... I just do a `pkill -9 git-credential-manager` whenever the machine starts crawling for no apparent reason...

**Comment by NightMachinery** [comment] 2023-05-20 17:30
<img width="763" alt="image" src="https://github.com/git-ecosystem/git-credential-manager/assets/36224762/6d8674b0-e9d4-4c93-b9dc-504fad4499a4">

These also drain the battery!

**Comment by joaocc** [comment] 2023-05-21 10:26
Any news on this front? Just to reinforce - opening git GUI clients sometimes launches 80 git-credential-manager processes and simply stops all other activity... Also happens once a day when the client decides it's time to fetch changes.

**Comment by mjcheetham** [comment] 2023-05-22 21:05
Please can you try installing the latest version of [GCM v2.1.2](https://github.com/git-ecosystem/git-credential-manager/releases/tag/v2.1.2), which has had some changes to improve performance.

With this latest version, you can also set the Git config variable `credential.trace` and capture trace info about what GCM is doing at the point that it hangs, the next time it occurs.

After installing the latest GCM, please can you run the following, and reproduce the issue, and then send/attach a copy of the log file:

```shell
git config --global credential.trace /tmp/gcm.log
```

**Comment by ldennington** [comment] 2023-10-30 21:21
Closing - this should be resolved on newer versions of GCM.

**Closed by ldennington** 2023-10-30 21:21 UTC
Labels: platform:osx, auth:microsoft, external

**Comment by forivall** [comment] 2023-10-31 15:45
Yup, I can confirm that this is resolved, as I haven't noticed the issue in the past few months (and I havent had to [run my script](https://github.com/git-ecosystem/git-credential-manager/issues/939#issuecomment-1476729290)). Thanks for the fix!
