### ISSUE TITLE
dotnet7 is EOL when  dotnet8 support is coming ?

### ISSUE THREAD

**Issue by stishkin** [git-ecosystem/git-credential-manager#1636] opened 2024-06-10 14:57 UTC
### Feature description

Installing as NET tool still requires dotnet7 

https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/install.md#net-tool

Any timeline for switching to dotnet8 ?

**Comment by rsanford-hh2** [comment] 2024-06-12 03:05
+1

**Comment by urtabajev** [comment] 2024-06-12 05:43
It is duplicate of #1606 as 2.5.0 has uses dotnet 8 but releasing to nuget.org seems to have issues. Workaround is to use tarball or source install until release issues are solved.

**Comment by xtqqczze** [comment] 2024-09-25 13:34
> We are currently facing some issues publishing a correctly signed package to Nuget.org. Due to recent sponsorship/corporate funding priority changes, work on GCM has unfortunately slowed significantly.
> 
> Please watch this space!

_Originally posted by @mjcheetham in https://github.com/git-ecosystem/git-credential-manager/issues/1606#issuecomment-2150748156_

**Comment by xtqqczze** [comment] 2024-09-30 16:39
> GCM 2.6 which targets .NET 8 has just been released on nuget.org
> 
> https://www.nuget.org/packages/git-credential-manager/2.6.0

_Originally posted by @mjcheetham in https://github.com/git-ecosystem/git-credential-manager/issues/1702#issuecomment-2383279743_

**Comment by mjcheetham** [comment] 2024-10-17 11:42
GCM 2.6.0 has been [released on nuget.org](https://www.nuget.org/packages/git-credential-manager/2.6.0), and we've also just [re-released 2.5.1 on nuget.org](https://www.nuget.org/packages/git-credential-manager/2.5.1) too. The [2.5.1 release on GitHub](https://github.com/git-ecosystem/git-credential-manager/releases/tag/v2.5.1) has also been updated with the re-signed NuGet package.

Note that the NuGet package for 2.5.0 will **not** be re-released.

**Closed by mjcheetham** 2024-10-17 11:42 UTC
Labels: enhancement
